### ISSUE TITLE
more flexibility?

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPluto/static-export-template#5]
thx a ton (using for my class)! 
would be cool to be able to:

- organize the notebooks e.g. into # homework, # lectures, # in-class activities sections
- have a list of ignored notebooks that don't build (tried to mimic MIT site and failed [here](https://github.com/SimonEnsemble/CHE-599-intro-to-data-science-Fall-2021/commit/39cafa962b9e4ba5340c0944f9e87159b0b824ef))
- be able to customize the `index.html` but not have it over-written each time I push a new notebook

**Comment by fonsp** [comment]
About 2: this is already a feature of PlutoSliderServer, your attempt didn't work because this line:

https://github.com/SimonEnsemble/CHE-599-intro-to-data-science-Fall-2021/commit/39cafa962b9e4ba5340c0944f9e87159b0b824ef#diff-48fcdbcf3daed39707fb9303956fadcb00bf92c3c24e569291cc777977aaf8c8R35

creates and activates a new temporary environment, which does not contain your PlutoDeployment.toml file

**Comment by fonsp** [comment]
About 3: can you make a new issue about this explaining in more detail what you mean?
